# Generated by Django 3.2.11 on 2022-04-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0002_orden_ordenid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='envio_total',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=9),
        ),
    ]
