# Generated by Django 3.2.11 on 2022-03-21 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cliente_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
