# Generated by Django 3.2.11 on 2022-03-27 17:16

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cart_products'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cartproduct',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
